// Canonical site URL. Every absolute URL (metadataBase, OG images,
// sitemap, robots, JSON-LD) derives from this one constant.
export const SITE_URL = "https://shaostassen.com";

export const SITE_NAME = "Shao Stassen";

export const SITE_DESCRIPTION =
  "Engineer working across embedded systems, robotics, and machine learning.";

/**
 * The site-wide OG image, generated by src/app/opengraph-image.tsx — which
 * reads its `size`/`alt` from here so there is one source of truth.
 *
 * It has to be stated as data as well as generated as a file: Next drops an
 * ancestor segment's file-convention image the moment a descendant declares
 * its own `openGraph` object, so `pageMetadata()` re-attaches it. Case
 * studies have their own opengraph-image.tsx in the same segment and keep
 * using the file convention instead.
 */
export const OG_IMAGE = {
  // Stating the URL by hand loses the content hash Next appends to its own
  // file-convention images, so `v` is the manual cache-buster: social
  // platforms key their cached preview on the exact URL. Bump it whenever
  // src/app/opengraph-image.tsx changes.
  url: "/opengraph-image?v=1",
  width: 1200,
  height: 630,
  type: "image/png",
  alt: "Shao Stassen — engineer",
} as const;
